version: '2.1'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: build/server/Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=go_api